// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD43-Qvgl0oHyffr6XLS5MwU4VKJw_LBac',
    appId: '1:242813078723:web:fd5ec8d42d1fcf3b4c6676',
    messagingSenderId: '242813078723',
    projectId: 'e-book-store-678f9',
    authDomain: 'e-book-store-678f9.firebaseapp.com',
    storageBucket: 'e-book-store-678f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc1eCBX7QSz6Qh87JswKjURkidHzM7M-c',
    appId: '1:242813078723:android:e03b781252d38c8c4c6676',
    messagingSenderId: '242813078723',
    projectId: 'e-book-store-678f9',
    storageBucket: 'e-book-store-678f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqewEYBs_4g94IbEXKiIcjpVx02TWNW3g',
    appId: '1:242813078723:ios:56753917833a7f744c6676',
    messagingSenderId: '242813078723',
    projectId: 'e-book-store-678f9',
    storageBucket: 'e-book-store-678f9.appspot.com',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqewEYBs_4g94IbEXKiIcjpVx02TWNW3g',
    appId: '1:242813078723:ios:1581f013aabc6e8a4c6676',
    messagingSenderId: '242813078723',
    projectId: 'e-book-store-678f9',
    storageBucket: 'e-book-store-678f9.appspot.com',
    iosBundleId: 'com.example.eBook.RunnerTests',
  );
}
